export const privacyTitles = (t:any) => [
    { id: "section1", text: t("privacyPolicy.titles.title1") },
    { id: "section2", text: t("privacyPolicy.titles.title2") },
    { id: "section3", text: t("privacyPolicy.titles.title3") },
    { id: "section4", text: t("privacyPolicy.titles.title4") },
    { id: "section5", text: t("privacyPolicy.titles.title5") },
    { id: "section6", text: t("privacyPolicy.titles.title6") },
    { id: "section7", text: t("privacyPolicy.titles.title7") },
    { id: "section8", text: t("privacyPolicy.titles.title8") },
    { id: "section9", text: t("privacyPolicy.titles.title9") },
    { id: "section10", text: t("privacyPolicy.titles.title10") },
    { id: "section11", text: t("privacyPolicy.titles.title11") },
    { id: "section12", text: t("privacyPolicy.titles.title12") },
    { id: "section13", text: t("privacyPolicy.titles.title13") },
  ];

  export const termsTitles = (t:any) => [
    { id: "section1", text: t("termsAndConditions.titles.title1") },
    { id: "section2", text: t("termsAndConditions.titles.title2") },
    { id: "section3", text: t("termsAndConditions.titles.title3") },
    { id: "section4", text: t("termsAndConditions.titles.title4") },
    { id: "section5", text: t("termsAndConditions.titles.title5") },
    { id: "section6", text: t("termsAndConditions.titles.title6") },
    { id: "section7", text: t("termsAndConditions.titles.title7") },
    { id: "section8", text: t("termsAndConditions.titles.title8") },
    { id: "section9", text: t("termsAndConditions.titles.title9") },
    { id: "section10", text: t("termsAndConditions.titles.title10") },
    { id: "section11", text: t("termsAndConditions.titles.title11") },
    { id: "section12", text: t("termsAndConditions.titles.title12") },
    { id: "section13", text: t("termsAndConditions.titles.title13") },
    { id: "section14", text: t("termsAndConditions.titles.title14") },
    { id: "section15", text: t("termsAndConditions.titles.title15") },
    { id: "section16", text: t("termsAndConditions.titles.title16") },
    { id: "section17", text: t("termsAndConditions.titles.title17") },
    { id: "section18", text: t("termsAndConditions.titles.title18") },
    { id: "section19", text: t("termsAndConditions.titles.title19") },
    { id: "section20", text: t("termsAndConditions.titles.title20") },
    { id: "section21", text: t("termsAndConditions.titles.title21") },
    { id: "section22", text: t("termsAndConditions.titles.title22") },
    { id: "section23", text: t("termsAndConditions.titles.title23") },
    { id: "section24", text: t("termsAndConditions.titles.title24") },
    { id: "section25", text: t("termsAndConditions.titles.title25") },
    { id: "section26", text: t("termsAndConditions.titles.title26") },
    { id: "section27", text: t("termsAndConditions.titles.title27") },
    { id: "section28", text: t("termsAndConditions.titles.title28") },
  ];


  export const faqForLawTitles = (t:any) => [
    { id: "section1", text: t("faqForLaw.titles.title1") },
    { id: "section2", text: t("faqForLaw.titles.title2") },
    { id: "section3", text: t("faqForLaw.titles.title3") },
    { id: "section4", text: t("faqForLaw.titles.title4") },
    { id: "section5", text: t("faqForLaw.titles.title5") },
    { id: "section6", text: t("faqForLaw.titles.title6") },
    { id: "section7", text: t("faqForLaw.titles.title7") },
    { id: "section8", text: t("faqForLaw.titles.title8") },

  ];
