on:
  push:
    branches:
      - main  

name: deploy

jobs:
  deploy:
    name: deploy cloud run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.LOGIN }}

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/francorutigliano/at3-front:prod
          
      - name: SSH and run command
        uses: appleboy/ssh-action@v0.1.3
        with:
             host: ${{ secrets.SSH_HOST }}
             port: ${{ secrets.SSH_PORT }}
             username: ${{ secrets.SSH_USERNAME }}
             password: ${{ secrets.SSH_PASSWORD }}
             script: |
               
               echo "Conexión SSH exitosa"

               /scriptsv2/deploy_front.sh
               